name: Deploy to Server

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: Install Yarn
        run: |
          npm install -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Remove old build files
        run: rm -rf ./dist

      - name: Build project
        run: yarn build

      - name: Stop existing PM2 process if running
        run: |
          if pm2 list | grep -q 'tourismContest'; then pm2 stop tourismContest; fi

      - name: Copy build files
        run: |
          cp -r ./dist /home/mschoi/Desktop/tourismContest/Spring-FE

      - name: Start server with PM2
        run: pm2 start /home/mschoi/Desktop/tourismContest/Spring-FE/server.js --name "tourismContest" --watch
